name: "Testing Suite"
on: [push, pull_request]

jobs:
  rust-test:
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest, ARM64]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init

      - name: Initialize Rust Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04' || matrix.platform == 'ARM64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run test suite
        working-directory: ./src-tauri
        run: cargo test

  ui-test:
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest, ARM64]
        node-version: [16]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install frontend dependencies
        run: pnpm install

      - run: pnpm run ui:test
